version: '3.8'

services:
  # ----------------------------------------------------
  # PostgreSQL Database Service (with PGVector Extension)
  # ----------------------------------------------------
  db:
    image: ankane/postgres-arm64-vector:latest # Recommended image with PGVector pre-installed
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      # The extension will be enabled by the backend on startup
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ----------------------------------------------------
  # FastAPI Backend Service
  # ----------------------------------------------------
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      # Set API Key environment variable for later RAG steps
      GEMINI_API_KEY: ${GEMINI_API_KEY} 
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

volumes:
  pg_data: